### ISSUE TITLE
步骤条省略中间应该是 已完成 （带颜色）

### ISSUE THREAD

**Issue by xiaohuoni** [CJY0208/mobile-components#1]
![image](https://user-images.githubusercontent.com/11746742/188349627-50f8d0e9-9d93-4ffe-8678-ae8aab6c3a9f.png)

**Comment by CJY0208** [comment]
很有道理

**Comment by xiaohuoni** [comment]
需要注意的是，后面的“省略” 是不带颜色，是正确的

**Comment by CJY0208** [comment]
修好了
